db-uri = "postgres://authenticator:authenticator@10.1.109.151:5432/huaguoshan_projd"
db-schemas = "api"
db-anon-role = "anonymous"
jwt-secret = "dev-postgrest-jwt-secret-change-me"
server-port = 13000
