-- 防御圈与研判因子配置：二维同心圆，版本追加，管理端只能通过受控 RPC 修改。
-- 依赖 api/admin/authenticator 角色与 PostGIS；不修改旧禁飞/临时管控区表。
begin;

create extension if not exists postgis;
create schema if not exists event_response;
revoke all on schema event_response from public;
grant usage on schema api to admin;

create table if not exists airspace.protected_object (
  id bigint generated by default as identity primary key,
  name text not null check (length(btrim(name)) between 1 and 120),
  geom geometry(Point,4326) not null,
  enabled boolean not null default true,
  current_version integer not null default 0 check (current_version >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint protected_object_lonlat_chk check (
    st_x(geom) between -180 and 180 and st_y(geom) between -90 and 90
  )
);
comment on table airspace.protected_object is '防御圈对应的保护对象，当前位置用于下一次发布；历史判圈使用版本固化中心。';
comment on column airspace.protected_object.geom is '保护对象当前 WGS84 中心点；修改后由新圈版本固化。';
comment on column airspace.protected_object.current_version is '当前发布的同心圈组版本；0 表示尚未发布。';

create table if not exists airspace.defense_ring (
  id bigint generated by default as identity primary key,
  protected_object_id bigint not null references airspace.protected_object(id),
  code text not null check (code in ('sensing','tracking','countermeasure','hard_strike','core')),
  version integer not null check (version > 0),
  name text not null,
  center_geom geometry(Point,4326) not null,
  radius_m numeric not null check (radius_m > 0 and radius_m <= 100000),
  ring_level smallint not null check (ring_level between 1 and 5),
  priority integer not null,
  valid_from timestamptz not null default now(),
  valid_to timestamptz,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique (protected_object_id, version, code),
  unique (protected_object_id, version, ring_level),
  check (valid_to is null or valid_to > valid_from)
);
comment on table airspace.defense_ring is '发布后的二维同心防御圈版本；历史中心、半径和优先级不可原地修改。';
comment on column airspace.defense_ring.center_geom is '发布时固化的 WGS84 圆心，历史研判引用本版本。';
comment on column airspace.defense_ring.radius_m is '防御圈水平地理半径，单位米，不包含高度范围。';
comment on column airspace.defense_ring.priority is '重叠时选圈优先级，数值越大越先选；不是风险分数。';
comment on column airspace.defense_ring.version is '同一保护对象的完整五层同心圈配置版本。';
create index if not exists defense_ring_center_geography_gix on airspace.defense_ring using gist ((center_geom::geography));
create index if not exists defense_ring_active_idx on airspace.defense_ring (protected_object_id, version);

create table if not exists event_response.risk_rule_set (
  id bigint generated by default as identity primary key,
  code text not null,
  version integer not null check (version > 0),
  status text not null check (status in ('draft','active','retired')),
  effective_from timestamptz not null default now(),
  effective_to timestamptz,
  created_at timestamptz not null default now(),
  unique (code, version)
);
comment on table event_response.risk_rule_set is '防御圈风险规则集的追加式版本及发布状态。';
comment on column event_response.risk_rule_set.version is '规则配置版本；发布后因子及参数不得修改。';
create unique index if not exists risk_rule_active_code_uq on event_response.risk_rule_set (code) where status = 'active';

create table if not exists event_response.risk_rule_factor (
  rule_set_id bigint not null references event_response.risk_rule_set(id),
  factor_code text not null,
  condition_code text not null,
  threshold_value numeric,
  unit text,
  score integer not null check (score between 0 and 100),
  exclusive_group text,
  enabled boolean not null default true,
  primary key (rule_set_id, factor_code)
);
comment on table event_response.risk_rule_factor is '固定编码的风险评分因子，不执行用户自定义条件或 SQL。';
comment on column event_response.risk_rule_factor.exclusive_group is '互斥因子组；同组只取最高适用档。';

create table if not exists event_response.risk_rule_parameter (
  rule_set_id bigint not null references event_response.risk_rule_set(id),
  parameter_code text not null,
  value_numeric numeric not null,
  unit text not null,
  primary key (rule_set_id, parameter_code)
);
comment on table event_response.risk_rule_parameter is '风险等级、轨迹窗口、确认和迟滞使用的数值参数及单位。';

-- 本环境 airspace 对新表可能有默认 admin DML 授权，必须显式撤销以保护已发布版本。
revoke all on airspace.protected_object,airspace.defense_ring,
  event_response.risk_rule_set,event_response.risk_rule_factor,event_response.risk_rule_parameter
  from public,anonymous,admin;
revoke all on sequence airspace.protected_object_id_seq,airspace.defense_ring_id_seq,
  event_response.risk_rule_set_id_seq from public,anonymous,admin;

-- 仅首次安装写入默认规则；重复执行迁移不覆盖管理员已发布的版本。
with initial as (
  insert into event_response.risk_rule_set (code,version,status)
  values ('defense-risk',1,'active') on conflict (code,version) do nothing returning id
)
insert into event_response.risk_rule_factor
  (rule_set_id,factor_code,condition_code,threshold_value,unit,score,exclusive_group)
select initial.id,v.factor_code,v.condition_code,v.threshold_value,v.unit,v.score,v.exclusive_group
from initial cross join (values
  ('zone_sensing','ring_level',1,'level',20,null),
  ('zone_tracking','ring_level',2,'level',35,null),
  ('zone_countermeasure','ring_level',3,'level',50,null),
  ('zone_hard_strike','ring_level',4,'level',70,null),
  ('zone_core','ring_level',5,'level',85,null),
  ('continuous_approach','closing_speed_min',2,'m/s',10,null),
  ('fast_approach','closing_speed_min',10,'m/s',5,null),
  ('next_ring_eta_60','eta_max',60,'s',10,'next_ring_eta'),
  ('next_ring_eta_30','eta_max',30,'s',20,'next_ring_eta'),
  ('identity_unverified','identity_unverified',null,null,5,null)
) as v(factor_code,condition_code,threshold_value,unit,score,exclusive_group);
with initial as (select id from event_response.risk_rule_set where code='defense-risk' and version=1)
insert into event_response.risk_rule_parameter(rule_set_id,parameter_code,value_numeric,unit)
select initial.id,v.code,v.value,v.unit from initial cross join (values
  ('score_low',20,'point'),('score_medium',40,'point'),('score_high',60,'point'),('score_critical',80,'point'),
  ('approach_window_seconds',10,'s'),('approach_min_points',4,'point'),
  ('confirm_observations',2,'point'),('upgrade_observations',2,'point'),
  ('downgrade_observations',5,'point'),('downgrade_outside_seconds',10,'s')
) as v(code,value,unit) on conflict do nothing;

-- 锁住发布内容；允许仅旧规则集状态切换为 retired，历史因子和参数保持原样。
create or replace function event_response.reject_published_rule_change() returns trigger
language plpgsql set search_path = pg_catalog, pg_temp as $$
begin
  if exists (select 1 from event_response.risk_rule_set where id = case when TG_OP='DELETE' then old.rule_set_id else new.rule_set_id end and status <> 'draft') then
    raise exception 'published rule content is immutable';
  end if;
  if TG_OP='DELETE' then return old; end if;
  return new;
end $$;
comment on function event_response.reject_published_rule_change() is '阻止已发布评分因子和参数被覆盖或删除，保留历史规则版本。';
drop trigger if exists risk_factor_immutable on event_response.risk_rule_factor;
create trigger risk_factor_immutable before update or delete on event_response.risk_rule_factor
for each row execute function event_response.reject_published_rule_change();
drop trigger if exists risk_parameter_immutable on event_response.risk_rule_parameter;
create trigger risk_parameter_immutable before update or delete on event_response.risk_rule_parameter
for each row execute function event_response.reject_published_rule_change();

create or replace function airspace.reject_ring_change() returns trigger
language plpgsql set search_path = pg_catalog, pg_temp as $$
begin
  raise exception 'published defense rings are immutable; publish a new version';
end $$;
comment on function airspace.reject_ring_change() is '阻止已发布防御圈版本被覆盖或删除，变更应发布新版本。';
drop trigger if exists defense_ring_immutable on airspace.defense_ring;
create trigger defense_ring_immutable before update or delete on airspace.defense_ring
for each row execute function airspace.reject_ring_change();

-- 读模型只暴露当前组；几何点以 GeoJSON 输出供前端显示。
create or replace function api.get_defense_ring_config() returns jsonb
language sql stable security definer set search_path = pg_catalog, public, pg_temp as $$
select jsonb_build_object(
  'objects', coalesce((select jsonb_agg(jsonb_build_object(
    'id',p.id,'name',p.name,'longitude',st_x(p.geom),'latitude',st_y(p.geom),
    'enabled',p.enabled,'version',p.current_version,
    'rings',coalesce((select jsonb_agg(jsonb_build_object(
      'id',r.id,'code',r.code,'name',r.name,'ring_level',r.ring_level,
      'radius_m',r.radius_m,'priority',r.priority,'version',r.version,
      'center',st_asgeojson(r.center_geom)::jsonb
    ) order by r.ring_level) from airspace.defense_ring r
    where r.protected_object_id=p.id and r.version=p.current_version),'[]'::jsonb)
  ) order by p.id) from airspace.protected_object p),'[]'::jsonb),
  'rules', (select jsonb_build_object('version',s.version,
    'factors',(select coalesce(jsonb_object_agg(f.factor_code,jsonb_build_object(
      'score',f.score,'condition_code',f.condition_code,'threshold_value',f.threshold_value,
      'unit',f.unit,'exclusive_group',f.exclusive_group,'enabled',f.enabled
    )),'{}'::jsonb) from event_response.risk_rule_factor f where f.rule_set_id=s.id),
    'parameters',(select coalesce(jsonb_object_agg(x.parameter_code,jsonb_build_object('value',x.value_numeric,'unit',x.unit)),'{}'::jsonb)
      from event_response.risk_rule_parameter x where x.rule_set_id=s.id))
    from event_response.risk_rule_set s where s.code='defense-risk' and s.status='active')
) $$;
comment on function api.get_defense_ring_config() is '返回 JSON 对象 {objects:[{id,name,longitude,latitude,enabled,version,rings:[{id,code,name,ring_level,radius_m,priority,version,center}]}],rules:{version,factors:{编码:{score,condition_code,threshold_value,unit,exclusive_group,enabled}},parameters:{编码:{value,unit}}}}。';

-- 整组五圈原子发布：没有“改一半”的配置，也不会修改历史版本。
create or replace function api.save_defense_ring_config(p_config jsonb) returns jsonb
language plpgsql security definer set search_path = pg_catalog, public, pg_temp as $$
declare
  v_id bigint;
  v_obj airspace.protected_object%rowtype;
  v_lon numeric;
  v_lat numeric;
  v_name text;
  v_enabled boolean;
  v_expected integer;
  v_version integer;
  v_radii numeric[];
  v_priorities integer[];
  v_codes text[] := array['sensing','tracking','countermeasure','hard_strike','core'];
  v_names text[] := array['感知圈','跟踪圈','反制圈','硬打击圈','核心圈'];
  i integer;
begin
  if p_config is null or jsonb_typeof(p_config) <> 'object' then raise exception 'configuration must be an object'; end if;
  v_name := btrim(p_config->>'name');
  if v_name is null or length(v_name) not between 1 and 120 then raise exception 'invalid protected object name'; end if;
  v_lon := (p_config->>'longitude')::numeric;
  v_lat := (p_config->>'latitude')::numeric;
  if v_lon is null or v_lat is null or v_lon not between -180 and 180 or v_lat not between -90 and 90 then
    raise exception 'invalid WGS84 center';
  end if;
  v_enabled := coalesce((p_config->>'enabled')::boolean,true);
  if jsonb_typeof(p_config->'radii_m') <> 'array' or jsonb_array_length(p_config->'radii_m') <> 5 then
    raise exception 'exactly five radii are required, outside to inside';
  end if;
  select array_agg(value::numeric order by ord) into v_radii
    from jsonb_array_elements_text(p_config->'radii_m') with ordinality as a(value,ord);
  if jsonb_typeof(p_config->'priorities') <> 'array' or jsonb_array_length(p_config->'priorities') <> 5 then
    raise exception 'exactly five priorities are required';
  end if;
  select array_agg(value::integer order by ord) into v_priorities
    from jsonb_array_elements_text(p_config->'priorities') with ordinality as a(value,ord);
  for i in 1..5 loop
    if v_radii[i] is null or v_radii[i] <= 0 or v_radii[i] > 100000 or v_priorities[i] is null then
      raise exception 'invalid radius or priority at level %',i;
    end if;
    if i > 1 and (v_radii[i] >= v_radii[i-1] or v_priorities[i] <= v_priorities[i-1]) then
      raise exception 'radii must decrease and priorities must increase toward core';
    end if;
  end loop;
  v_id := nullif(p_config->>'id','')::bigint;
  if v_id is null then
    if p_config ? 'expected_version' and (p_config->>'expected_version')::integer <> 0 then
      raise exception 'new protected object expected_version must be zero';
    end if;
    insert into airspace.protected_object(name,geom,enabled,current_version)
      values (v_name,st_setsrid(st_makepoint(v_lon,v_lat),4326),v_enabled,1) returning * into v_obj;
  else
    v_expected := (p_config->>'expected_version')::integer;
    if v_expected is null then raise exception 'expected_version required for update'; end if;
    select * into v_obj from airspace.protected_object where id=v_id for update;
    if not found then raise exception 'protected object % does not exist',v_id; end if;
    if v_obj.current_version <> v_expected then raise exception 'stale protected object version: expected %, actual %',v_expected,v_obj.current_version; end if;
    update airspace.protected_object set name=v_name,geom=st_setsrid(st_makepoint(v_lon,v_lat),4326),
      enabled=v_enabled,current_version=current_version+1,updated_at=now()
      where id=v_id returning * into v_obj;
  end if;
  v_version := v_obj.current_version;
  for i in 1..5 loop
    insert into airspace.defense_ring(protected_object_id,code,name,version,center_geom,radius_m,ring_level,priority)
      values (v_obj.id,v_codes[i],v_names[i],v_version,v_obj.geom,v_radii[i],i,v_priorities[i]);
  end loop;
  return jsonb_build_object('id',v_obj.id,'version',v_version);
end $$;
comment on function api.save_defense_ring_config(jsonb) is '原子保存保护对象与五层圆形防御圈；输入 JSON {id?,expected_version?,name,longitude,latitude,enabled,radii_m:[外到内五个米值],priorities:[外到内五个递增整数]}，返回 {id,version}；旧圈版本不修改。';

-- 规则分数只能在固定因子编码集合内调整，复制条件和参数到下个不可变版本。
create or replace function api.save_defense_risk_scores(p_expected_version integer,p_scores jsonb) returns jsonb
language plpgsql security definer set search_path = pg_catalog, public, pg_temp as $$
declare
  v_old event_response.risk_rule_set%rowtype;
  v_new_id bigint;
  v_key text;
  v_score integer;
  v_scores integer[];
begin
  if p_scores is null or jsonb_typeof(p_scores) <> 'object' or
    (select count(*) from jsonb_object_keys(p_scores)) <> 10 then
    raise exception 'exactly ten factor scores required';
  end if;
  -- Locks a stable parent row to serialize concurrent publishes even when versions change.
  perform 1 from event_response.risk_rule_set where code='defense-risk' and version=1 for update;
  select * into v_old from event_response.risk_rule_set where code='defense-risk' and status='active' for update;
  if not found or v_old.version <> p_expected_version then raise exception 'stale risk rule version'; end if;
  for v_key in select factor_code from event_response.risk_rule_factor where rule_set_id=v_old.id loop
    if not p_scores ? v_key or jsonb_typeof(p_scores->v_key) <> 'number' then raise exception 'missing or invalid factor %',v_key; end if;
    v_score := (p_scores->>v_key)::integer;
    if v_score not between 0 and 100 then raise exception 'score must be between 0 and 100'; end if;
  end loop;
  if exists (select 1 from jsonb_object_keys(p_scores) k where not exists
    (select 1 from event_response.risk_rule_factor f where f.rule_set_id=v_old.id and f.factor_code=k)) then
    raise exception 'unknown factor code';
  end if;
  select array_agg((p_scores->>('zone_'||code))::integer order by ord) into v_scores
    from unnest(array['sensing','tracking','countermeasure','hard_strike','core']) with ordinality as x(code,ord);
  if v_scores[1] < 20 or v_scores[2] <= v_scores[1] or v_scores[3] <= v_scores[2] or
    v_scores[4] <= v_scores[3] or v_scores[5] <= v_scores[4] then
    raise exception 'zone scores must increase from sensing to core, sensing at least 20';
  end if;
  update event_response.risk_rule_set set status='retired',effective_to=now() where id=v_old.id;
  insert into event_response.risk_rule_set(code,version,status)
    values ('defense-risk',v_old.version+1,'active') returning id into v_new_id;
  insert into event_response.risk_rule_factor(rule_set_id,factor_code,condition_code,threshold_value,unit,score,exclusive_group,enabled)
    select v_new_id,factor_code,condition_code,threshold_value,unit,(p_scores->>factor_code)::integer,exclusive_group,enabled
      from event_response.risk_rule_factor where rule_set_id=v_old.id;
  insert into event_response.risk_rule_parameter(rule_set_id,parameter_code,value_numeric,unit)
    select v_new_id,parameter_code,value_numeric,unit from event_response.risk_rule_parameter where rule_set_id=v_old.id;
  return jsonb_build_object('version',v_old.version+1);
end $$;
comment on function api.save_defense_risk_scores(integer,jsonb) is '发布新评分版本；输入预期版本和 {因子编码:0～100整数}（完整十项），旧参数与条件复制；返回 {version}，不改写历史研判。';

revoke all on function api.get_defense_ring_config() from public,anonymous;
revoke all on function api.save_defense_ring_config(jsonb) from public,anonymous;
revoke all on function api.save_defense_risk_scores(integer,jsonb) from public,anonymous;
grant execute on function api.get_defense_ring_config() to admin;
grant execute on function api.save_defense_ring_config(jsonb) to admin;
grant execute on function api.save_defense_risk_scores(integer,jsonb) to admin;
commit;
